config/routes.rb
AcademicoRails::Application.routes.draw do

  

  #resources :registration_admission_types

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :registrations => "users/registrations",
                                       :confirmations => "users/confirmations",
                                       :sessions => 'devise/sessions' },
             :skip => [:sessions, :registrations] do
    get  'entrar'   => "devise/sessions#new",       :as => :new_user_session
    post 'entrar'  => 'devise/sessions#create',    :as => :user_session
    get 'sair'  => 'devise/sessions#destroy',   :as => :destroy_user_session
    get "assinar" => "academicusers/user_registrations#new",   :as => :new_user_registration
    #get '/auth/:provider/callback' => 'users/omniauth_callbacks#create'

  end
  get '/auth/:provider/callback' => 'users/omniauth_callbacks#create'

  match 'states/update_state_select/:id', :controller=>'states', :action => 'update_state_select'
  match 'cities/update_city_select/:id', :controller=>'cities', :action => 'update_city_select'
  match 'cities/autocomplete_city_name', :controller=>'cities', :action => 'autocomplete_city_name'
  match 'discipline_classes/update_discipline_select/:id', :controller=>'discipline_classes', :action => 'update_discipline_select'


  root :to => 'welcome#index'
  
  # Tabelas Básicas do SISTEMA
  
  #######################################
  # Menusuperior de Registro Academicos #
  #######################################
  resources :registro_academico, :controller => 'menu/registro_academico', :only => [:index], :path => 'registro_academico'
  # Matrículas
  resources :registrations, :path =>"registro_academico/matriculas" do
      resources :registration_classes, :path =>"enturmacoes"
  end
  # Pessoas
  resources :people, :path =>"registro_academico/pessoas" do
    resources :people_telephones, :path =>"telefones"
    resources :person_addresses, :path =>"enderecos"
    resources :person_identification_docs, :path => "documentacao"
    resources :person_person_type_depts
    

    get :pesquisar, :on => :collection
    resources :registrations, :path =>"matriculas" do
        resources :registration_classes, :path =>"enturmacoes"
    end
  end
  # Departamento
  resources :depts, :path => "registro_academico/departamentos" do
    resources :courses, :path => "cursos"
    resources :teaching_equipaments, :path => "equipamentosdeensino"
    resources :dept_addresses, :path => "enderecos"
    resources :dept_telephones, :path => "telefones"
  end
  # Matriz  Curricular
  resources :course_matrices, :path => "registro_academico/matrizcurricular" do
    # Disciplinas da Matriz
    resources :matrix_disciplines, :path => "disciplinas" do
      # pré requisitos
      resources :matrix_discipline_prerequisites, :path => "prerequisitos"
    end
    # grade horaria da Matriz
    resources :timetables, :path =>"gradehoraria" do
      resources :timetable_class_times, :path =>"horas"
    end
    #importa grade horaria
    match 'import_matrix_timetable', :controller=>'course_matrices', :method => :put, :action => 'import_matrix_timetable'
    
    # turmas da Matriz
    resources :school_classes, :path =>"turmas" do
      resources :discipline_classes, :path =>"componentescurriculares" do
        resources :class_teachings, :path =>"docencias"
        resources :class_records, :path =>"aulas" do
            resources :class_record_presences, :path => "presencas"
        end
        resources :discipline_class_exams, :path => "avaliacoes" do
            resources :discipline_class_exam_results, :path => "notas"
            match 'import_registration_to_exam_result', :controller=>'discipline_class_exam_results', :method => :put, :action => 'import_registration_to_exam_result'
        end
      end
    end
    # Regras acadêmicas da Matriz
    resources :course_matrix_academic_rules, :path => "regrasacademicas" do
      put :register_rules, :on => :collection
    end
    #match 'register_rules', :controller=>'course_matrix_academic_rules', :method => :put, :action => 'register_rules'
  end
  
  # Turmas
  resources :school_classes, :path =>"registro_academico/turmas" do
    # Classes das turmas
    resources :discipline_classes, :path =>"componentescurriculares" do
      resources :class_teachings, :path =>"docencias"
      resources :class_records, :path =>"aulas" do
          resources :class_record_presences, :path => "presencas"
      end
      resources :discipline_class_exams, :path => "avaliacoes" do
          resources :discipline_class_exam_results, :path => "notas"
          match 'import_registration_to_exam_result', :controller=>'discipline_class_exam_results', :method => :put, :action => 'import_registration_to_exam_result'
      end
    end
  end  

  # Classes  
  resources :discipline_classes, :path =>"registro_academico/componentescurriculares" do
    #match 'close', :controller=>'discipline_classes', :method => :put, :action => 'close'
    put 'close'
    resources :class_teachings, :path =>"docencias"
    # Aulas ministradas
    resources :class_records, :path =>"aulas" do
        
        get :class_record_presences_day, :on => :collection # Chamada de uma classe por dia
        put 'update_presences_by_date', :on => :collection, :controller => :class_records, :action => 'update_presences_by_date'
        
        resources :class_record_presences, :path => "presencas"
        get :classdateselect, :on => :collection # calendário para inclusao de aulas
        get :new_many, :on => :collection # inclusao de varias aulas
        post :create_many, :on => :collection # create de varias aulas
        match 'presencas', :controller=>'class_record_presences', :method => :put, :action => 'update_presence'
        match 'import', :controller=>'class_record_presences', :method => :put, :action => 'import_registration_to_presence'
    end
    # Avaliações
    resources :discipline_class_exams, :path => "avaliacoes" do
        resources :discipline_class_exam_results, :path => "notas"
        match 'notas', :controller=>'discipline_class_exam_results', :method => :put, :action => 'update_results'
        match 'import_registration_to_exam_result', :controller=>'discipline_class_exam_results', :method => :put, :action => 'import_registration_to_exam_result'
    end
    resources :registration_classes, :path =>"enturmacoes"
    match 'enturmacoes', :controller=>'registration_classes', :method => :put, :action => 'create_registration_classes'
  end
  
  # Oferta de Vagas
  resources :course_vacancies, :path => "registro_academico/ofertadevagas"
  # Periodo Letivo
  resources :class_seasons, :path => "registro_academico/periodosletivos"
  # Cursos
  resources :courses, :path => "registro_academico/cursos" do
      resources :disciplines, :path => "registro_academico/disciplinas"
  end
  # Regras acadêmicas
  resources :academic_rules, :path => 'registro_academico/regras_academicas'
  
  resources :config, :controller => 'menu/config', :only => [:index], :path => 'configuracoes'
  scope "configuracoes" do  
    #################################
    # Menusuperior de Configurações #
    #################################
    resources :races, :path => 'etnias'
    resources :admission_types, :path => 'tipos_de_ingressos'
    resources :ways_of_admissions, :path => 'formas_de_ingressos'
    resources :precedence_schools, :path => 'precedencias_escolares'
    resources :special_needs_types, :path => 'tipo_necessidade_especial'
    resources :marital_statuses, :path => 'estado_civil'
    resources :education_degrees, :path => 'niveis_educacionais'
    resources :genders, :path => 'sexos'
    resources :blood_types, :path => 'tipos_sanguineos'
    resources :knowledge_areas, :path => "areas_conhecimento"
    resources :registration_schemes, :path => "sistema_registro"
    resources :learning_modalities, :path => "modalidades_ensino"
    resources :education_modalities, :path => "modalidades"
    resources :education_steps, :path => "graus" 
    resources :education_levels, :path => "niveis"
    resources :techaxis_types, :path => "eixos" do
     resources :techaxes, :path => "areas"
    end
    resources :provenance_areas, :path => 'procedencia'
    resources :street_types, :path => 'logradouro'
    resources :telephone_types, :path => 'telefones'
    resources :class_season_types, :path => 'periodos'
    resources :matrix_evaluation_types, :path => 'matriz_avaliacoes'
    resources :matrix_statuses, :path => 'estados'
    resources :discipline_types, :path => 'disciplinas'
    resources :countries, :path => 'paises' do
     resources :states, :path => 'estados' do
      resources :cities, :path => 'cidades'
     end
    end

    resources :class_times, :path => 'horarios'
    resources :day_weeks, :path => 'dias_semana'
    resources :equipament_types, :path => 'equipamento'
    resources :situation_teaching_equipaments, :path => 'estado_equipamento'
    resources :shift_types, :path => "turnos"


    resources :academic_rule_types, :path => 'regras_academicas'
    resources :discipline_class_exam_types, :path => 'exames'
    resources :class_record_types, :path => 'tipos_registro'
    resources :registration_class_statuses, :path => 'situacao_curricular'
    resources :registration_statuses, :path => 'situacao_matricula'
    resources :course_statuses, :path => 'cursos'
    resources :class_student_statuses, :path => 'estados_estudante'
    resources :military_document_types, :path => 'documentos_militar'
    resources :issuing_institutions, :path => 'emissoras'
    resources :matrix_discipline_groups, :path => 'matriz_disciplina'
    resources :dept_types, :path => 'departamentos'

    
    #users_role  
    resources :user_roles, :path => "acesso"    

  end
  
  #espaço do professor
  resources :teacher, :controller => 'teacher/dashboard', :path => 'professor' do      

app/controllers/matrix_evaluation_types_controller.rb
class MatrixEvaluationTypesController < ApplicationController
  load_and_authorize_resource
  # GET /matrix_evaluation_types
  # GET /matrix_evaluation_types.json
  def index
    @matrix_evaluation_types = MatrixEvaluationType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @matrix_evaluation_types }
    end
  end

  # GET /matrix_evaluation_types/1
  # GET /matrix_evaluation_types/1.json
  def show
    @matrix_evaluation_type = MatrixEvaluationType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @matrix_evaluation_type }
    end
  end

  # GET /matrix_evaluation_types/new
  # GET /matrix_evaluation_types/new.json
  def new
    @matrix_evaluation_type = MatrixEvaluationType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @matrix_evaluation_type }
    end
  end

  # GET /matrix_evaluation_types/1/edit
  def edit
    @matrix_evaluation_type = MatrixEvaluationType.find(params[:id])
  end

  # POST /matrix_evaluation_types
  # POST /matrix_evaluation_types.json
  def create
    @matrix_evaluation_type = MatrixEvaluationType.new(params[:matrix_evaluation_type])

    respond_to do |format|
      if @matrix_evaluation_type.save
        format.html { redirect_to @matrix_evaluation_type, :notice => 'Avaliação de Matriz criada com sucesso.' }
        format.json { render :json => @matrix_evaluation_type, :status => :created, :location => @matrix_evaluation_type }
      else
        format.html { render :action => "new" }
        format.json { render :json => @matrix_evaluation_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /matrix_evaluation_types/1
  # PUT /matrix_evaluation_types/1.json
  def update
    @matrix_evaluation_type = MatrixEvaluationType.find(params[:id])

    respond_to do |format|
      if @matrix_evaluation_type.update_attributes(params[:matrix_evaluation_type])
        format.html { redirect_to @matrix_evaluation_type, :notice => 'Avaliação de Matriz atualizada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @matrix_evaluation_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /matrix_evaluation_types/1
  # DELETE /matrix_evaluation_types/1.json
  def destroy
    @matrix_evaluation_type = MatrixEvaluationType.find(params[:id])
    @matrix_evaluation_type.destroy

    respond_to do |format|
      format.html { redirect_to matrix_evaluation_types_url, :notice => 'Avaliação de Matriz excluída com sucesso.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/matrix_evaluation_types_helper.rb
module MatrixEvaluationTypesHelper
end

app/views/matrix_evaluation_types/_form.html.erb
<%= form_for @matrix_evaluation_type, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                matrix_evaluation_types_path, :class => 'btn' %>
  </div>
<% end %>

app/views/matrix_evaluation_types/edit.html.erb
<%- model_class = @matrix_evaluation_type.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/matrix_evaluation_types/index.html.erb
<%- model_class = MatrixEvaluationType.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @matrix_evaluation_types.each do |matrix_evaluation_type| %>
      <tr>
        <td><%= link_to matrix_evaluation_type.id, matrix_evaluation_type_path(matrix_evaluation_type) %></td>
        <td><%= matrix_evaluation_type.description %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_matrix_evaluation_type_path(matrix_evaluation_type), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      matrix_evaluation_type_path(matrix_evaluation_type),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => t("controller_message.delete_confirm"))),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_matrix_evaluation_type_path,
            :class => 'btn btn-primary' %>

app/views/matrix_evaluation_types/new.html.erb
<%- model_class = @matrix_evaluation_type.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/matrix_evaluation_types/show.html.erb
<%- model_class = @matrix_evaluation_type.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @matrix_evaluation_type.description %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              matrix_evaluation_types_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_matrix_evaluation_type_path(@matrix_evaluation_type), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              matrix_evaluation_type_path(@matrix_evaluation_type),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => t("controller_message.delete_confirm"))),
              :class => 'btn btn-danger' %>
</div>