config/routes.rb
AcademicoRails::Application.routes.draw do

  

  #resources :registration_admission_types

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :registrations => "users/registrations",
                                       :confirmations => "users/confirmations",
                                       :sessions => 'devise/sessions' },
             :skip => [:sessions, :registrations] do
    get  'entrar'   => "devise/sessions#new",       :as => :new_user_session
    post 'entrar'  => 'devise/sessions#create',    :as => :user_session
    get 'sair'  => 'devise/sessions#destroy',   :as => :destroy_user_session
    get "assinar" => "academicusers/user_registrations#new",   :as => :new_user_registration
    #get '/auth/:provider/callback' => 'users/omniauth_callbacks#create'

  end
  get '/auth/:provider/callback' => 'users/omniauth_callbacks#create'

  match 'states/update_state_select/:id', :controller=>'states', :action => 'update_state_select'
  match 'cities/update_city_select/:id', :controller=>'cities', :action => 'update_city_select'
  match 'cities/autocomplete_city_name', :controller=>'cities', :action => 'autocomplete_city_name'
  match 'discipline_classes/update_discipline_select/:id', :controller=>'discipline_classes', :action => 'update_discipline_select'


  root :to => 'welcome#index'
  
  # Tabelas Básicas do SISTEMA
  
  #######################################
  # Menusuperior de Registro Academicos #
  #######################################
  resources :registro_academico, :controller => 'menu/registro_academico', :only => [:index], :path => 'registro_academico'
  # Matrículas
  resources :registrations, :path =>"registro_academico/matriculas" do
      resources :registration_classes, :path =>"enturmacoes"
  end
  # Pessoas
  resources :people, :path =>"registro_academico/pessoas" do
    resources :people_telephones, :path =>"telefones"
    resources :person_addresses, :path =>"enderecos"
    resources :person_identification_docs, :path => "documentacao"
    resources :person_person_type_depts
    

    get :pesquisar, :on => :collection
    resources :registrations, :path =>"matriculas" do
        resources :registration_classes, :path =>"enturmacoes"
    end
  end
  # Departamento
  resources :depts, :path => "registro_academico/departamentos" do
    resources :courses, :path => "cursos"
    resources :teaching_equipaments, :path => "equipamentosdeensino"
    resources :dept_addresses, :path => "enderecos"
    resources :dept_telephones, :path => "telefones"
  end
  # Matriz  Curricular
  resources :course_matrices, :path => "registro_academico/matrizcurricular" do
    # Disciplinas da Matriz
    resources :matrix_disciplines, :path => "disciplinas" do
      # pré requisitos
      resources :matrix_discipline_prerequisites, :path => "prerequisitos"
    end
    # grade horaria da Matriz
    resources :timetables, :path =>"gradehoraria" do
      resources :timetable_class_times, :path =>"horas"
    end
    #importa grade horaria
    match 'import_matrix_timetable', :controller=>'course_matrices', :method => :put, :action => 'import_matrix_timetable'
    
    # turmas da Matriz
    resources :school_classes, :path =>"turmas" do
      resources :discipline_classes, :path =>"componentescurriculares" do
        resources :class_teachings, :path =>"docencias"
        resources :class_records, :path =>"aulas" do
            resources :class_record_presences, :path => "presencas"
        end
        resources :discipline_class_exams, :path => "avaliacoes" do
            resources :discipline_class_exam_results, :path => "notas"
            match 'import_registration_to_exam_result', :controller=>'discipline_class_exam_results', :method => :put, :action => 'import_registration_to_exam_result'
        end
      end
    end
    # Regras acadêmicas da Matriz
    resources :course_matrix_academic_rules, :path => "regrasacademicas" do
      put :register_rules, :on => :collection
    end
    #match 'register_rules', :controller=>'course_matrix_academic_rules', :method => :put, :action => 'register_rules'
  end
  
  # Turmas
  resources :school_classes, :path =>"registro_academico/turmas" do
    # Classes das turmas
    resources :discipline_classes, :path =>"componentescurriculares" do
      resources :class_teachings, :path =>"docencias"
      resources :class_records, :path =>"aulas" do
          resources :class_record_presences, :path => "presencas"
      end
      resources :discipline_class_exams, :path => "avaliacoes" do
          resources :discipline_class_exam_results, :path => "notas"
          match 'import_registration_to_exam_result', :controller=>'discipline_class_exam_results', :method => :put, :action => 'import_registration_to_exam_result'
      end
    end
  end  

  # Classes  
  resources :discipline_classes, :path =>"registro_academico/componentescurriculares" do
    #match 'close', :controller=>'discipline_classes', :method => :put, :action => 'close'
    put 'close'
    resources :class_teachings, :path =>"docencias"
    # Aulas ministradas
    resources :class_records, :path =>"aulas" do
        
        get :class_record_presences_day, :on => :collection # Chamada de uma classe por dia
        put 'update_presences_by_date', :on => :collection, :controller => :class_records, :action => 'update_presences_by_date'
        
        resources :class_record_presences, :path => "presencas"
        get :classdateselect, :on => :collection # calendário para inclusao de aulas
        get :new_many, :on => :collection # inclusao de varias aulas
        post :create_many, :on => :collection # create de varias aulas
        match 'presencas', :controller=>'class_record_presences', :method => :put, :action => 'update_presence'
        match 'import', :controller=>'class_record_presences', :method => :put, :action => 'import_registration_to_presence'
    end
    # Avaliações
    resources :discipline_class_exams, :path => "avaliacoes" do
        resources :discipline_class_exam_results, :path => "notas"
        match 'notas', :controller=>'discipline_class_exam_results', :method => :put, :action => 'update_results'
        match 'import_registration_to_exam_result', :controller=>'discipline_class_exam_results', :method => :put, :action => 'import_registration_to_exam_result'
    end
    resources :registration_classes, :path =>"enturmacoes"
    match 'enturmacoes', :controller=>'registration_classes', :method => :put, :action => 'create_registration_classes'
  end
  
  # Oferta de Vagas
  resources :course_vacancies, :path => "registro_academico/ofertadevagas"
  # Periodo Letivo
  resources :class_seasons, :path => "registro_academico/periodosletivos"
  # Cursos
  resources :courses, :path => "registro_academico/cursos" do
      resources :disciplines, :path => "registro_academico/disciplinas"
  end
  # Regras acadêmicas
  resources :academic_rules, :path => 'registro_academico/regras_academicas'
  
  resources :config, :controller => 'menu/config', :only => [:index], :path => 'configuracoes'
  scope "configuracoes" do  
    #################################
    # Menusuperior de Configurações #
    #################################
    resources :races, :path => 'etnias'
    resources :admission_types, :path => 'tipos_de_ingressos'
    resources :ways_of_admissions, :path => 'formas_de_ingressos'
    resources :precedence_schools, :path => 'precedencias_escolares'
    resources :special_needs_types, :path => 'tipo_necessidade_especial'
    resources :marital_statuses, :path => 'estado_civil'
    resources :education_degrees, :path => 'niveis_educacionais'
    resources :genders, :path => 'sexos'
    resources :blood_types, :path => 'tipos_sanguineos'
    resources :knowledge_areas, :path => "areas_conhecimento"
    resources :registration_schemes, :path => "sistema_registro"
    resources :learning_modalities, :path => "modalidades_ensino"
    resources :education_modalities, :path => "modalidades"
    resources :education_steps, :path => "graus" 
    resources :education_levels, :path => "niveis"
    resources :techaxis_types, :path => "eixos" do
     resources :techaxes, :path => "areas"
    end
    resources :provenance_areas, :path => 'procedencia'
    resources :street_types, :path => 'logradouro'
    resources :telephone_types, :path => 'telefones'
    resources :class_season_types, :path => 'periodos'
    resources :matrix_evaluation_types, :path => 'matriz_avaliacoes'
    resources :matrix_statuses, :path => 'estados'
    resources :discipline_types, :path => 'disciplinas'
    resources :countries, :path => 'paises' do
     resources :states, :path => 'estados' do
      resources :cities, :path => 'cidades'
     end
    end

    resources :class_times, :path => 'horarios'
    resources :day_weeks, :path => 'dias_semana'
    resources :equipament_types, :path => 'equipamento'
    resources :situation_teaching_equipaments, :path => 'estado_equipamento'
    resources :shift_types, :path => "turnos"


    resources :academic_rule_types, :path => 'regras_academicas'
    resources :discipline_class_exam_types, :path => 'exames'
    resources :class_record_types, :path => 'tipos_registro'
    resources :registration_class_statuses, :path => 'situacao_curricular'
    resources :registration_statuses, :path => 'situacao_matricula'
    resources :course_statuses, :path => 'cursos'
    resources :class_student_statuses, :path => 'estados_estudante'
    resources :military_document_types, :path => 'documentos_militar'
    resources :issuing_institutions, :path => 'emissoras'
    resources :matrix_discipline_groups, :path => 'matriz_disciplina'
    resources :dept_types, :path => 'departamentos'

    
    #users_role  
    resources :user_roles, :path => "acesso"    

  end
  
  #espaço do professor
  resources :teacher, :controller => 'teacher/dashboard', :path => 'professor' do      

app/helpers/discipline_classes_helper.rb
module DisciplineClassesHelper
  def h_status_color(rclass)
   if @discipline_class.ending_at?
    rclass.registration_class_status.is_approved ? "alert alert-info" : "alert alert-error"
   end
  end
end

app/views/discipline_classes/_disciplines.html.erb
 <% if !disciplines.blank?  %>
    <%= select_tag 'discipline_class[matrix_discipline_id]', options_from_collection_for_select(disciplines, "id", "discipline_name"), :class => 'select_field', :prompt => "...Selecione...", :class => 'field span8' %>
 <% else %>
    <%= select_tag 'discipline_class[matrix_discipline_id]', [], :class => 'select_field', :prompt => "...Selecione...", :class => 'field span8'  %>
 <% end %>

app/views/discipline_classes/_exams.html.erb
<div class="span12">
  <div class="well">
      <fieldset>
          <%= link_to "<div style='font-size: 16px;  padding-top:4px; '><i class='icon-pencil'></i> Avaliações </div>".html_safe,
            "#{request.fullpath}/avaliacoes", :class => 'btn btn-inverse span12' %>
         <div style="padding-top: 60px">
	     <% if @discipline_class.discipline_class_exams.count > 0 %>
		       <table class="table table-condensed table-bordered table-hover">
				<thead>
				 <tr> 	
				   <th><center>#</center></th>	
				   <th><center>Aluno</center></th>	
				   <th><center><%= link_to '%', "#", :rel => "tooltip", "data-placement"=>"top", "data-original-title" => "Percentual de Presenças", :disabled => true %></center></th>	
	               <% @discipline_class.discipline_class_exams.each_with_index do |exam, i| %>
				      <th rowspan="2"><center><%=link_to ( (exam.applied_at ? I18n.l(exam.applied_at) : 'sem data') + '<br/>' + exam.title).html_safe, "#{request.fullpath}/avaliacoes/#{exam.id}/notas" %></center></th>
			       <%end%>
   			       <th><center>Média<br/>( ∑(n*p) / ∑(p) )</center></th>
   	               <th><center>Situação</center></th>	
				 </tr>					
			    </thead>
			    <tbody>
	               <% @discipline_class.registration_classes.sort_by(&:student_name).each_with_index do |rclass, i| %>
	                 <% if !rclass.registration.registration_status.is_attending.blank? %>
				      <tr class="<%= h_status_color(rclass)%>">
    					<td><%= i+1 %></td>
					    <td> <%= link_to rclass.student_name, discipline_class_registration_class_path(@discipline_class,rclass) %></td>
					    <td><center><%= rclass.frequency %></center></td>
						<% @discipline_class.discipline_class_exams.each_with_index do |exam, i| %>
						   <%nota = DisciplineClassExamResult.where(:discipline_class_exam_id => exam.id).where(:registration_class_id => rclass.id).first.try(:result) %>
						   <td><center> <h5><%= (nota.blank? ? '0.0' : nota.to_s) %> <small>x<%=exam.weight%></small></h5> </center></td>
					    <%end%>
					       <td><center> <h5> <%= rclass.model_student_result_average.round(2) %> </h5></center></td>	
					       <td>
						    <center> 
						       <h6><%= rclass.registration_class_status_final.description %></h6>
						    </center>
						   </td>	
					  </tr>
					  <% else %>
					  <!--caso a pessoa matriculada nao possa comparecer por causa da situacao matricular nao imprime nada-->
					  <% end %>
			       <%end%>				
			  </tbody>
		     </table> 
		<%else%>
		      <dd><center><%= '...sem avaliação cadastrada...' if @discipline_class.discipline_class_exams.count == 0 %></center></dd>
		<% end %>			    
         </div>
      </fieldset>
      <fieldset>
		 <div class="btn-group pull-left">
	     	<!-- Informações de regras academicas -->
	        <ul>
		     <h5>Regras acadêmicas:</h5>
		        <ul>
			      <%if @discipline_class.school_class.course_matrix.course_matrix_academic_rules.count > 0 %>
					 <%@discipline_class.school_class.course_matrix.course_matrix_academic_rules.each do |rules|%>
				      <li><%= rules.academic_rule.academic_rule_type.rule %> <%= rules.academic_rule.operator %> <%= rules.academic_rule.value %>%</li>
				     <%end%>					     
					  <ul class="unstyled">
						 <%= form_for @discipline_class, :url => discipline_class_close_path(@discipline_class), :html => { :class => 'form-horizontal'} do |f| %>
						      <% classe_fechada = (@discipline_class.ending_at? ? "Componente Curricular fechado" : "Fechar Componente Curricular") %>
					       	  <%= f.submit classe_fechada, :class => 'btn btn-primary', :class => "btn btn btn-success", :disabled => (true if @discipline_class.ending_at?) %>
					     <%end%>
					    
					  </ul>
				  <%else%>
				      <div class="alert alert-error">
					     <h5>Nenhuma regra acadêmica definida na matriz deste curso</h5>
					     <center><%=link_to "<i class='icon-th-list'></i> Incluir regras".html_safe, course_matrix_course_matrix_academic_rules_path(@discipline_class.school_class.course_matrix), :class => "btn btn-mini btn-primary" %></center>
					  </div>
				  <%end%>
			    </ul>				 
		    </ul>
			<!-- -->
		 </div>
		  <div class=" btn-group pull-right">
			  <a class="btn dropdown-toggle btn-small" data-toggle="dropdown" href="#">
			    <i class='icon-print'></i>Imprimir Mapa de Notas
			    <span class="caret"></span>
			  </a>
			  <ul class="dropdown-menu">
			    <li><%= link_to "Preenchido", discipline_class_path(@discipline_class, :format =>  "pdf", :report_discipline => "class_exams", :preenchido => true ), :tabindex => "-1" %></li>
				<li><%= link_to "Em Branco", discipline_class_path(@discipline_class, :format =>  "pdf", :report_discipline => "class_exams" ), :tabindex => "-1" %></li>
			  </ul>
		  </div>
	  </fieldset>
  </div>
</div>	

app/views/discipline_classes/_formbyschoolclass.html.erb
<%= form_for [@school_class, @discipline_class], :html => { :class => 'form-horizontal' } do |f| %>
<h2><%=  @school_class.model_custom_name %></h2>
	<div class="control-group">
	  <%= f.label :matrix_discipline_id, :class => 'control-label' %>
	    <div class="controls"  id="turmaDisciplinas"> 
		     <%= select_tag 'discipline_class[matrix_discipline_id]', options_from_collection_for_select(@school_class.course_matrix.matrix_disciplines, "id", "discipline_name"), :class => 'select_field', :prompt => "...Selecione...", :class => 'field span8' %>
	    </div>
	</div>

  <div class="control-group">
    <%= f.label :code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :code, :class => 'text_field', :class => 'field span3'  %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :vancancies, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :vancancies, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :started_at, :class => 'control-label' %>
    <div class="controls">
      <%  @discipline_class.started_at = @discipline_class.started_at.try(:strftime, "%d.%m.%Y")%>
      <%= f.text_field :started_at, :class => 'datepicker_class', :style => "width:80px" %>
    </div>
  </div>

<%if !(action_name == "new" or action_name == "create") %>
 <div class="control-group">	
    <%= f.label :ending_at, :class => 'control-label' %>
    <div class="controls">
      <%  @discipline_class.ending_at = @discipline_class.ending_at.try(:strftime, "%d.%m.%Y") %>
      <%= f.text_field :ending_at, :class => 'datepicker_class', :include_blank => true, :style => "width:80px" %>
    </div>	  	
  </div>
<% end %>

  <div class="control-group">
    <%= f.label :timetable_started_at, :class => 'control-label' %>
    <div class="controls">
      <% @discipline_class.timetable_started_at = @discipline_class.timetable_started_at.try(:strftime, "%d.%m.%Y") %>
      <%= f.text_field :timetable_started_at, :class => 'datepicker_class', :include_blank => true, :style => "width:80px" %>
    </div>
  </div>

  <div class="form-actions">
	<%= f.submit nil, :class => 'btn btn-primary' %>
	<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
	              school_class_discipline_classes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/discipline_classes/index.html.erb
<%- model_class = DisciplineClass.new.class -%>
<div class="page-header">
  <h1><i class="icon-pencil"></i> <%=t '.title', :default => model_class.model_name.human.pluralize %>
	<%= form_tag discipline_classes_path, :method => :get, :class => 'form-search pull-right' do %>
	    <%= text_field_tag :search, params[:search], :placeholder => "Pesquisar...", :class => 'search-query' %>
		<button type="submit" class="btn">
		  <i class='icon-search'></i> Ok
		</button>
	<% end %>
  </h1>
</div>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:school_class_id) %></th>
      <th><%= model_class.human_attribute_name(:matrix_discipline_id) %></th>
      <th><%= model_class.human_attribute_name(:docentes) %></th>
      <th><%= model_class.human_attribute_name(:class_records) %></th>
      <th><%= model_class.human_attribute_name(:discipline_class_exams) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @discipline_classes.each do |discipline_class| %>
      <tr>

        <td><small><%= link_to discipline_class.id, discipline_class_path(discipline_class) %></small></td>
        <td><small><%= link_to discipline_class.school_class.try(:identifier), discipline_class_path(discipline_class) %></small></td>
        <td><small><%= discipline_class.matrix_discipline.try(:discipline_name) %></small></td>
        <td><small><%= link_to "<i class='icon-user'></i> ".html_safe + discipline_class.class_teachings.count.to_s, discipline_class_class_teachings_path(discipline_class) %></small></td>
        <td><small><%= link_to "<i class='icon-pencil'></i> ".html_safe + discipline_class.class_records.count.to_s, discipline_class_class_records_path(discipline_class) %></small></td>
        <td><small><%= link_to "<i class='icon-align-justify'></i> ".html_safe + discipline_class.discipline_class_exams.count.to_s, discipline_class_discipline_class_exams_path(discipline_class) %></small></td>

        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_discipline_class_path(discipline_class), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      discipline_class_path(discipline_class),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => t("controller_message.delete_confirm"))),
                      :class => 'btn btn-mini btn-danger' %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>
<center><small><%= will_paginate @discipline_classes %></small></center>

<%if params[:school_class_id]%>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_school_class_discipline_class_path,
            :class => 'btn btn-primary' %>
<%else%>
	<%= link_to t('.new', :default => t("helpers.links.new")),
	            new_discipline_class_path,
	            :class => 'btn btn-primary' %>
<%end%>

app/views/discipline_classes/show.html.erb
<%- model_class = @discipline_class.class -%>
<div class="page-header">
  <h1><i class="icon-pencil"></i> <%=t '.title', :default => model_class.model_name.human %></h1>
</div>
<div class="row-fluid">
<div class="container span12">
	<fieldset>
		<br/>
		<dl class="dl-horizontal span6">
		  <dt><strong><%= SchoolClass.human_attribute_name(:matrix_id) %>:</strong></dt>
		  <dd><%=link_to "#{@discipline_class.school_class.course_matrix.id} - #{@discipline_class.school_class.course_matrix.started_at_formatted}", course_matrix_path(@discipline_class.school_class.course_matrix)%></dd>		
		  <dt><strong><%= model_class.human_attribute_name(:school_class_id) %>:</strong></dt>
		  <dd><%= link_to "#{@discipline_class.school_class.identifier}", school_class_path(@discipline_class.school_class.identifier) %> </dd>
		  <dt><strong><%= model_class.human_attribute_name(:matrix_discipline_id) %>:</strong></dt>
		  <dd><%= @discipline_class.matrix_discipline.discipline_name if @discipline_class.matrix_discipline_id %></dd>
		  <dt><strong><%= model_class.human_attribute_name(:code) %>:</strong></dt>
		  <dd><strong><%= @discipline_class.code %></strong></dd>

		</dl>
		<dl class="dl-horizontal span5">
		  <dt><strong><%= model_class.human_attribute_name(:vancancies) %>:</strong></dt>
		  <dd><%= @discipline_class.vancancies %></dd>
		  <dt><strong><%= model_class.human_attribute_name(:started_at) %>:</strong></dt>
		  <dd><%=l @discipline_class.started_at if @discipline_class.started_at %></dd>
		  <dt><strong><%= model_class.human_attribute_name(:ending_at) %>:</strong></dt>
		  <dd><%=l @discipline_class.ending_at if @discipline_class.ending_at %></dd>
		  <dt><strong><%= model_class.human_attribute_name(:timetable_started_at) %>:</strong></dt>
		  <dd><%=l @discipline_class.timetable_started_at if @discipline_class.timetable_started_at %></dd>
		</dl>
	   </div>
	
	<div class="form-actions">
	  <%= link_to "<i class='icon-undo'></i> ".html_safe + t('.back', :default => t("helpers.links.back")),
	              :back, :class => 'btn btn-mini'  %>
	  <%= link_to "<i class='icon-edit'></i> ".html_safe + t('.edit', :default => t("helpers.links.edit")),
	              "#{request.fullpath}/edit", :class => 'btn btn-mini' %>
	  <%= link_to "<i class='icon-pencil'></i> ".html_safe + t('Aulas'),
				   "#{request.fullpath}/aulas", :class => 'btn btn-mini' %>
	  <%= link_to "<i class='icon-user'></i> ".html_safe + t('Docentes'),
				   discipline_class_class_teachings_path(@discipline_class), :class => 'btn btn-mini' %>
	  <%= link_to "<i class='icon-align-justify'></i> ".html_safe + t('Avaliações'),
				   discipline_class_discipline_class_exams_path(@discipline_class), :class => 'btn btn-mini' %> 

	  <%= link_to "<i class='icon-group'></i> ".html_safe + t('Enturmação'),
	               "#{request.fullpath}/enturmacoes", :class => 'btn btn-mini' %> 


	  <%= link_to "<i class='icon-trash'></i> ".html_safe + t('.destroy', :default => t("helpers.links.destroy")),
	              discipline_class_path(@discipline_class),
	              :method => 'delete',
	              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => t("controller_message.delete_confirm"))),
	              :class => 'btn btn-danger btn-mini' %>
	</div>
	
	</fieldset>
	<!-- Docentes -->
	<div class="span12">
	  <div class="well">
	      <fieldset>
	          <%= link_to "<div style='font-size: 16px;  padding-top:4px; '><i class='icon-user'></i> Docentes </div>".html_safe,
	            discipline_class_class_teachings_path(@discipline_class), :class => 'btn btn-inverse span12' %>
	         <div style="padding-top: 60px">
	           <% @discipline_class.class_teachings.each do |teacher| %>
			    <dd><%= teacher.user.try(:displayname) %></dd>
			  <%end%>
			    <dd><center><%= '...sem docente vinculado...' if @discipline_class.class_teachings.count == 0 %></center></dd>
	         </div>
	      </fieldset>
	  </div>
	</div>

	<!-- Aulas -->
	<div class="span12">
	  <div class="well">
	      <fieldset>
	          <%= link_to "<div style='font-size: 16px;  padding-top:4px; '><i class='icon-pencil'></i> Aulas </div>".html_safe,
	            "#{request.fullpath}/aulas", :class => 'btn btn-inverse span12' %>
	         <div style="padding-top: 60px">
		       <table class="table table-striped table-condensed">
	           <% @discipline_class.class_records.each_with_index do |record, i| %>
			    <tr><td><%= I18n.localize(record.recorded_at) %> <%= record.class_time.try(:model_custom_name)%> <%= record.record%></td></tr>
			    <% break if i == 5 %>
				<%end%>
    			<tr><td><%= link_to "...mais...", "#{request.fullpath}/aulas" %></td></tr>
			  </table> 
			    <dd><center><%= '...sem aula cadastrada...' if @discipline_class.class_records.count == 0 %></center></dd>
	         </div>
	      </fieldset>
	      <fieldset>
		  <div class=" btn-group pull-left">
		  		<%= link_to "<i class='icon-calendar'></i> Grade Horária do Professor".html_safe,
		  		   classdateselect_discipline_class_class_records_path(@discipline_class),
		  		   :class => 'btn' %>
		  </div>
	      <div class=" btn-group pull-left">
			  <a class="btn dropdown-toggle btn-small" data-toggle="dropdown" href="#">
			    <i class='icon-print'></i> Conteúdo Ministrado
			    <span class="caret"></span>
			  </a>
			  <ul class="dropdown-menu">
			    <li><%= link_to "Preenchido", discipline_class_path(@discipline_class, :format =>  "pdf", :report_discipline => "school_class", :preenchido => true ), :tabindex => "-1" %></li>
				<li><%= link_to "Em Branco", discipline_class_path(@discipline_class, :format =>  "pdf", :report_discipline => "school_class" ), :tabindex => "-1" %></li>
			  </ul>
		  </div>
		  <div class=" btn-group pull-right">
			  <a class="btn dropdown-toggle btn-small" data-toggle="dropdown" href="#">
			    <i class='icon-print'></i> Diário de Frequência
			    <span class="caret"></span>
			  </a>
			  <ul class="dropdown-menu">
			    <li><%= link_to "Preenchido", discipline_class_path(@discipline_class, :format =>  "pdf", :report_discipline => "class_record", :preenchido => true ), :tabindex => "-1" %></li>
				<li><%= link_to "Em Branco", discipline_class_path(@discipline_class, :format =>  "pdf", :report_discipline => "class_record" ), :tabindex => "-1" %></li>
				<li><%= link_to "Lista de Presença", discipline_class_path(@discipline_class, :format => "pdf", :report_discipline => "presence_list"), :tabindex => "-1" %><li>
			  </ul>
		  </div>
		  </fieldset>
	  </div>
	</div>	
	
	<!-- Avaliacoes -->
	<%= render :partial => 'exams' %> 

  </div>
</div>

</div>